fn check_error() -> Result<(), ()> {
    Ok(())
}

fn main() {
    let _ = check_error();
}
